### PR TITLE
Added search params to the Mod Logs and Approvals   and reports page

### LINKED ISSUE #118: Feature: Make links shareable
**What do you want to see?**
If you change something ( filters etc... ) that should be represented in the url for the user to save as a bookmark or share to other users.

### PR DESCRIPTION
**Pull request by Pdzly**
closes #118

This PR adds, to all pages search params, for users to save their filters.

### CODE REVIEW

**Comment by tgxn** [comment]
ideally, all of these settings would be tracked using the configReducer and saved to localStorage aswell, having these in state will make writing the filter UI easier - for example my UI for searching for users will just have to dispatch to config instead of passing parameters

**Comment by tgxn** [comment]
maybe we  have a seperate reducer for anything that is ephemeral, and shouldn't be saved in localStorage...

**Comment by Pdzly** [comment]
I didnt do that because then it would be not the "React way". As then i would need to use native functions. And we would need to check if it will create a infinite loop. Because => dispatch event => changes url search params => the search params gets "changed" => dispatch event => repeat 

Because you cant use react hooks in redux actions

**Comment by Pdzly** [comment]
Ohh now i understood you. But that is not the reason why the url search params are there. Its for sharing to others, bookmark multiple filters.... if i understood you now correct

**Comment by Pdzly** [comment]
@tgxn what is now the change i should do? For me this PR is fine for the first instance. If we find something better we can do that.

**Comment by tgxn** [comment]
yeah sorry this looks great @Pdzly :) srry i've been sidetracked the past few weeks 😑

i think i was asking this so that we can have other elements control the state, but it looks fine 😊

**Comment by Pdzly** [comment]
Thanks!

**Pull request merged**
